# Generated by Django 4.2.4 on 2023-08-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="large_language_model",
            field=models.CharField(
                blank=True,
                choices=[("gpt-4", "Gpt 4"), ("llama2", "Llama2")],
                default="gpt-4",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subscribed_to_emails",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
